# Generated by Django 4.1.3 on 2023-02-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre_equipo', max_length=50)),
                ('calificacion', models.FloatField(blank=True, db_column='calificacion_equipo', null=True)),
                ('maestro_asesor', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Informacion de Equipo',
                'verbose_name_plural': 'Informacion de Equipos',
                'db_table': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='maestroAsesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre_equipo', max_length=50)),
            ],
            options={
                'verbose_name': 'Informacion de Maestro Asesor',
                'verbose_name_plural': 'Informacion de Maestros Asesores',
                'db_table': 'maestroAsesor',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RelacionEquipoJuez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_juez', models.PositiveIntegerField(db_column='id_juez')),
                ('id_equipo', models.PositiveIntegerField(db_column='id_equipo')),
                ('calificacion', models.FloatField(blank=True, db_column='calificacion_equipo', null=True)),
                ('nombre_juez', models.CharField(db_column='nombre_juez', max_length=200)),
                ('nombre_equipo', models.CharField(db_column='nombre_equipo', max_length=200)),
            ],
            options={
                'verbose_name': 'Informacion de la Relacion',
                'verbose_name_plural': 'Informacion de las Relaciones',
                'db_table': 'Asignaciones',
                'default_permissions': (),
                'unique_together': {('id_juez', 'id_equipo')},
            },
        ),
    ]
