# Generated by Django 4.1.3 on 2022-11-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.FloatField(db_column='calificacion_equipo', null=True)),
            ],
            options={
                'verbose_name': 'Informacion de Equipo',
                'verbose_name_plural': 'Informacion de Equipos',
                'db_table': 'Equipo',
                'default_permissions': (),
            },
        ),
    ]
