# Generated by Django 4.1.3 on 2022-11-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(blank=True, db_column='nombre_equipo', max_length=50, null=True),
        ),
    ]
