# Generated by Django 4.1.3 on 2022-11-25 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipo',
            options={'verbose_name': 'Informacion de Equipo', 'verbose_name_plural': 'Informacion de Equipos'},
        ),
    ]
