# Generated by Django 4.1.3 on 2022-11-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_equipo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='calificacion',
            field=models.FloatField(blank=True, db_column='calificacion_equipo', null=True),
        ),
    ]
