# Generated by Django 4.1.3 on 2022-11-16 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_rename_juez_relacionequipojuez_nombre_juez'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relacionequipojuez',
            name='equipo',
        ),
        migrations.RemoveField(
            model_name='relacionequipojuez',
            name='nombre_juez',
        ),
    ]
