# Generated by Django 4.1.3 on 2022-11-07 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0003_alter_equipo_calificacion'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='equipo',
            table='Equipos',
        ),
    ]
