# Generated by Django 4.1.3 on 2022-11-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0003_remove_relacionequipojuez_equipo_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='relacionequipojuez',
            constraint=models.UniqueConstraint(fields=('id_juez', 'id_equipo'), name='unique_relation'),
        ),
    ]
