# Generated by Django 4.1.3 on 2022-11-16 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0004_relacionequipojuez_unique_relation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='relacionequipojuez',
            name='unique_relation',
        ),
        migrations.AlterUniqueTogether(
            name='relacionequipojuez',
            unique_together={('id_juez', 'id_equipo')},
        ),
    ]
