# Generated by Django 4.1.3 on 2022-11-10 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipos', '0004_alter_equipo_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuecesEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.FloatField(blank=True, db_column='calificacion_equipo', null=True)),
                ('equipo', models.ForeignKey(db_column='equipo', on_delete=django.db.models.deletion.CASCADE, to='equipos.equipo')),
                ('juez', models.ForeignKey(db_column='juez', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Informacion de Relacion',
                'verbose_name_plural': 'Informacion de Relaciones',
                'db_table': 'Relacion',
                'default_permissions': (),
            },
        ),
    ]
